# Site settings
title: time.destroy_all
header-img: img/home-bg.png
email: rafeeq-123@hotmail.com
copyright_name: rafeeq-123
description: > # this means to ignore newlines until "baseurl:"
  The Balance
baseurl: "" # the subpath of your site, e.g. /blog
twitter_username: 
github_username:  rafeeq-123
learn_profile: rafeeq-123
email_username: rafeeq-123@hotmail.com

# Build settings
markdown: kramdown
highlighter: rouge
permalink: pretty
paginate: 5
exclude: ["less","node_modules","Gruntfile.js","package.json","README.md"]

gems: [jekyll-paginate, jekyll-feed]
